#!/bin/bash

# Install dependencies depending of the distribution family
echo "Download dependencies"

if which yum &> /dev/null; then
   echo "You are in the RedHat family"   
   sudo yum install gcc-c++ make 
else
   echo "You are in the Debian family"
   sudo apt-get install gcc make build-essential
fi

# CONSTANT
VERSION=2.2.12
DIRECTORY=/usr/local

#DIRS
SCRIPT=$(readlink -f $0)
BASEDIR=`dirname $SCRIPT`

# Redis Installation
cd /tmp
wget http://redis.googlecode.com/files/redis-$VERSION.tar.gz
tar xzf redis-$VERSION.tar.gz
cd redis-$VERSION
make

# Move Redis installation to $DIRECTORY
sudo mv /tmp/redis-$VERSION $DIRECTORY/redis

# Create Redis user/group
sudo groupadd redis
sudo useradd -c "redis" -g redis -r -s /bin/bash redis

# Permissions
sudo chown -R redis:redis $DIRECTORY/redis

# Modification of the configuration file for Redis
cd $DIRECTORY/redis
sudo mv redis.conf redis-default.conf
sudo cp $BASEDIR/conf/redis.conf redis.conf 

# Edit sysctl.conf to fix WARNING on Redis startup
FIX_WARNING="vm.overcommit_memory = 1"
sudo echo $FIX_WARNING >> /etc/sysctl.conf
sudo sysctl vm.overcommit_memory=1

# Test
if which redis-server &> /dev/null; then
   echo "Successfully installed Redis"
else
   echo "Failed to install Redis"
fi

# 
cd $DIRECTORY/bin 
ln -s $DIRECTORY/redis/src/redis-server redis-server
ln -s $DIRECTORY/redis/src/redis-cli redis-cli

# Set runlevel & Install init.d startup for redis-server
if which yum &> /dev/null; then
   sudo cp $BASEDIR/init.d/redhat/redis-server /etc/init.d/redis-server
   sudo chkconfig redis-server --add
   sudo chkconfig --level 235 redis-server on 
else
   sudo cp $BASEDIR/init.d/debian/redis-server /etc/init.d/redis-server
   sudo update-rc.d redis-server defaults
fi
 
# Start redis
sudo /etc/init.d/redis-server start

# Clean up
sudo rm -R $BASEDIR
sudo rm /tmp/redis-$VERSION.tar.gz
